services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - app-node-modules:/app/node_modules
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    environment:
      CI: 'true'
      PORT: ${PORT:-3000}
    develop:
      watch:
        - action: restart
          path: package.json

volumes:
  app-node-modules:
